"$schema" = 'https://starship.rs/config-schema.json'

scala.disabled = true
nodejs.disabled = true

[time]
disabled = false
utc_time_offset = "0"
time_format = "%R"
format = "[$time UTC]($style) "

[character]
success_symbol = "[->](green)"
error_symbol = "[!->](bold red)"
vicmd_symbol = "[V](bold green)"
