general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = /etc/wallpaper.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 1
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 600, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    outer_color = rgba(182, 73, 73, 0.7)
    inner_color = rgba(255, 255, 182, 1)
    font_color = rgba(0, 0, 36, 1.0)
    shadow_passes = 4
    shadow_size = 2
    shadow_color = rgb(0,0,0)
    shadow_boost = 4.2
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <i>...</i>
    hide_input = false
    rounding = -1
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 200
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, 130
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H:%M:%S")"
    text_align = center
    color = rgba(255, 255, 182, 1)
    shadow_passes = 4
    shadow_size = 2
    shadow_color = rgb(0,0,0)
    shadow_boost = 10.2
    font_size = 150
    font_family = FiraCode Nerd Font Mono Bold
    position = 0, 250
    halign = center
    valign = bottom
}
