#!/bin/sh

calendar() {
LOCK_FILE="$HOME/.cache/eww-calendar.lock"

run() {
    eww open calendar
}

if [[ ! -f "$LOCK_FILE" ]]; then
    eww close system music_win audio_ctl
    touch "$LOCK_FILE"
    run
else
    eww close calendar
    rm "$LOCK_FILE"
fi
}


system() {
LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"

run() {
    eww open system
}

if [[ ! -f "$LOCK_FILE_MEM" ]]; then
    eww close calendar music_win audio_ctl
    touch "$LOCK_FILE_MEM"
    run
else
    eww close system
    rm "$LOCK_FILE_MEM"
fi
}


music() {
LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"

run() {
    eww open music_win
}

if [[ ! -f "$LOCK_FILE_SONG" ]]; then
    eww close system calendar
    touch "$LOCK_FILE_SONG"
    run
else
    eww close music_win
    rm "$LOCK_FILE_SONG"
fi
}



audio() {
LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"

run() {
    eww open audio_ctl
}

if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
    eww close system calendar music
    touch "$LOCK_FILE_AUDIO"
    run
else
    eww close audio_ctl
    rm "$LOCK_FILE_AUDIO"
fi
}


case $1 in
  calendar) calendar;;
  system) system;;
  music) music;;
  audio) audio;;
esac
