# Generated by bin/scripts/gh-dash-repos — do not edit by hand.
# Repos per context that gh-dash watches for notifications.
# Regenerate: gh-dash-repos   (then rebuild)
# Last generated: 2026-09-24, activity since 2025-09-24.
{
  SA = [
    "structured-abstraction/saskartsboard-collections"
    "structured-abstraction/calgaryundergroundfilm.org"
    "structured-abstraction/strabs-iac"
    "structured-abstraction/implemus.com"
    "structured-abstraction/alzheimercalgary.ca"
    "structured-abstraction/structuredabstraction.com"
    "structured-abstraction/swim"
    "structured-abstraction/swim-compromised"
    "structured-abstraction/ciffcalgary.ca"
    "structured-abstraction/sled-ng"
    "structured-abstraction/structuredabstraction.com-payload"
    "structured-abstraction/juggernaut"
  ];
  Narrative = [
    "narrative-io/narrative-workspace-template"
    "narrative-io/narrative-marketplace-backend"
    "narrative-io/mintlify-docs"
    "narrative-io/code-reviews"
  ];
  BigGeo = [
    "BigGeo-GIV/bg-asterisk"
    "BigGeo-GIV/bg-core"
    "BigGeo-GIV/DevOps"
  ];
  lichess = [
    "lichess-org/lila"
    "lichess-org/mobile"
    "lichess-org/scalachess"
    "Lichess4545/heltour"
    "Lichess4545/Chesster"
  ];
}
